### ISSUE TITLE
Thoughts

### ISSUE THREAD

**Issue by JPeer264** [aichbauer/node-semantic-git-release-cli#1]
Let's sum up, what should this project basically do:

It should `tag` a new version on Git (first off just Github support, if others have it differently). Based on the new commits since the last version there is an `suggested version bump`, but other version bumps are still suggested (like [np](https://www.npmjs.com/package/np)). The commits should get sorted and written into `CHANGELOG.md` (like [eslint](https://github.com/eslint/eslint/blob/master/CHANGELOG.md)). If possible it should also write the release notes on Github.

Available functions until first stable release:
- [x] Get all commits since last tag (if there is one)-
- [x] Bump version
- [x] Get persons name of Merged Branch/Commit
- [x] Tag version on git (and push them)
- [x] available by CLI (inquirer?)
- [x] all steps should be shown with [listr](https://www.npmjs.com/package/listr)

Mighty features:
- [ ] suggested version bump (based on commits)

Should anything be different or are there any additional suggestions?

**Comment by rudolfsonjunior** [comment]
Yes, that sum it up pretty good. What is `listr` basically doing?

**Comment by JPeer264** [comment]
You define tasks, and `listr` does these tasks step by step and show it in the shell:

<img src="https://raw.githubusercontent.com/SamVerschueren/listr/9193ddd4a8d4850e6bed2093dc9547d4994e31b9/media/screenshot.gif" />

**Comment by rudolfsonjunior** [comment]
Thats good, the description on the npm website does not have this gif, so i did nit really understand what they were doing, but I was thinking about something like that too. Sounds great.

**Comment by aichbauer** [comment]
Closed because suggested version can be confusing if the order of the versions will differ every time.
