### ISSUE TITLE
Remove node_modules should be async

### ISSUE THREAD

**Issue by JPeer264** [aichbauer/node-semantic-git-release-cli#26]
As of here, the node_modules are getting removed synchronously: 
https://github.com/aichbauer/node-semantic-git-release-cli/blob/656ead894cec2a39f40f8b745e26bb7972d24dfa/lib/helpers/cleanNodeModules.js#L8

But sync code will hold the entire node process until it gets finished, that's why listr won't show up until it is finished.

**Comment by aichbauer** [comment]
closed by #27
