### ISSUE TITLE
Run script before release

### ISSUE THREAD

**Issue by JPeer264** [aichbauer/node-semantic-git-release-cli#30]
It would be nice to run a script before it is released. Such as a `npm run build`, in case I also want to publish the `dist` folder of an library.

**Comment by aichbauer** [comment]
That is a good idea... this would be required for a feature like #23

**Comment by JPeer264** [comment]
Actually now I am using `prepublish` as this is called right after `npm i`. This is now a pretty good workaround 👍

**Comment by aichbauer** [comment]
this is better to be handled via npm scripts
