### ISSUE TITLE
Wrong alpha/beta/rc release

### ISSUE THREAD

**Issue by JPeer264** [aichbauer/node-semantic-git-release-cli#7]
Alpha Beta and RC are usually used if the version has currently no fresh major version released.

So, if I am at `0.0.1` I expect the alpha to be `1.0.0-alpha.0` currently it is on `0.0.2-alpha.0`. If I am at `1.0.0-alpha.4` I expect the version bumps to be at:
```sh
1.0.0
1.0.0-alpha.5
1.0.0-beta.0
1.0.0-rc.0
Other (specify)
```

**Comment by aichbauer** [comment]
I use the [semver package](https://www.npmjs.com/package/semver) which is used by npm itself.

`semver.inc('0.0.1', 'prerelease', 'alpha')` outputs exactly `0.0.2-alpha.0`

if you are on `semver.inc('1.2.3', 'prerelease', 'beta')` it leads to `1.2.4-beta.0` as I expect that every increment from a stable version is seen as a patch version.

and if you are on a alpha version like `semver.inc('1.0.0-alpha.4', 'prerelease', 'alpha')` it will lead exactly to the outcome what you described in your post.

**Comment by JPeer264** [comment]
But I will never reach `1.0.0-alpha.4` without having a stable release. So first I have to publish `1.0.0` to get `1.0.0-alpha.0`. Or am I wrong?

**Comment by aichbauer** [comment]
> 4. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

I think if you have a number under `1.0.0` the people should know they are working with an unstable version.

> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0. 

And if you want to bump it to `1.0.0-alpha`you can do it manually, I dont think it is good to over go the rules npm is using themself in [semver](https://www.npmjs.com/package/semver)

**Comment by JPeer264** [comment]
I think you got the point there :+1:
