### ISSUE TITLE
No Username Password Prompt

### ISSUE THREAD

**Issue by JPeer264** [aichbauer/node-semantic-git-release-cli#9]
When I wanted to release a new version I got stuck at "release new version", because I had to prompt my "Username" and "Password" for git (I wasn't using ssh). So it might be helpful to show the prompt of git and remove it after it was successful.

![username](https://user-images.githubusercontent.com/10677263/29157970-629c3b9c-7da9-11e7-9433-f93f95b9e004.png)

**Comment by aichbauer** [comment]
If I get this right, you want to use the command `sgr` and then we should check if you could push to the repository. If this is not possible we should show the login prompt (username and pw). Then you fill it out and then we start with the tasks?

**Comment by JPeer264** [comment]
Or we should not check and just pass the output of the console here.

**Comment by aichbauer** [comment]
Like

```js
if (canNotPush(cwd)) {
  console.error('Some Error');
}
```

**Comment by JPeer264** [comment]
Does this line work with `listr` https://github.com/JPeer264/node-semantic-git-commit-cli/blob/master/lib/cli.js#L25

The option `{ stdio: 'inherit' }`, this would show every shell output. We can't always assume that the credentials are needed.

**Comment by aichbauer** [comment]
You can add whatever you want inside of a `listr` task.

[Release-Task](https://github.com/aichbauer/node-semantic-git-release-cli/blob/master/lib/sub-tasks/release.js)

I could add the option `{ stdio: 'inherit' }` in every `execa.shell` function inside the release tasks... Do you think it should be on every `execa.shell` function, not only in the release tasks? Or should we add it only to `execa.shell('git push --follow-tags')` to `.shell('git push --follow-tags', { stdio: 'inherit' })`?

**Comment by JPeer264** [comment]
I guess for now it is just here relevant. If we need it somewhere else, we can always add it :)

**Comment by aichbauer** [comment]
@JPeer264 I cannot reproduce the scenario... So you were working on a different computer? The `git config` was with a different username and an different email? You tried to release on a repo where you did not have any rights?

**Comment by aichbauer** [comment]
close due to no response
